### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by Howuhh** [corl-team/xland-minigrid#1]
## Roadmap

~~Approx v1.0 release: February 2024~~

### General
- [x] type hints
- [ ] ~~tests~~
- [x] documentation and examples
- [x] environment registration
- [x] colab notebooks with examples 
 
### Baselines
- [x] PPO+RNN baselines (single task, meta-rl)
- [ ]  ~~open wandb reports + configs to reproduce paper figures~~
- [x] multi-gpu training

###  Tiles
- [x] Key (like in Minigrid)
- [x] Door (like in Minigrid)
- [ ] ~~Box (like in Minigrid) (may reduce FPS!!!)~~

### Actions
- [ ] ~~stochasticity~~ (could be done with a wrapper)

### Rules & Goals
- [x] procedural generator (like in xland v2)
- [x] pre-sampled benchmarks, 1M+ tasks

### Map
- [x] different grid layouts (mazes, rooms, objects)

### Envs
- [x] porting majority of minigrid envs
- [x] full xland procedural meta-env
- [x] observation/action spaces
- [x] calibrate `max_steps` with available benchmarks and baselines
- [x] provide rgb image observations 

### Beyond v1.0 directions
- [ ] stable env API (from gymnasium function_env ?)
- [ ] gymnasium adapters & wrappers
- [ ] multi-agent version (highly unlikely)
- [ ] MAML baselines, Mamba instead of GRU?
- [ ] Dataset + offline baselines ([AD](https://arxiv.org/abs/2210.14215), [DPT](https://arxiv.org/abs/2306.14892))
- [ ] procedural maze generation compatible with jit
- [ ] new INTERESTING rules and goals
- [ ] fast FOV algorithm for see_through_walls=False
- [ ] goals composition (OR, AND, NOT)
- [ ] ~~masked rules as a part of the observation~~ (could be done with a wrapper)
- [ ] rules descriptions with language
- [ ] porting multiroom, moving obstacles, safety envs from minigrid
